# Generated by Django 4.2.5 on 2023-09-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='e-mail')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_time', models.TimeField(auto_now_add=True, verbose_name='время')),
                ('frequency', models.CharField(choices=[('0', 'не повторять'), ('1', 'ежедневно'), ('2', 'еженедельно'), ('3', 'ежемесячно')], default='0', max_length=15, verbose_name='периодичность')),
                ('status', models.CharField(choices=[('0', 'создана'), ('1', 'запущена'), ('2', 'завершена')], default='0', max_length=15, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_time', models.DateTimeField(auto_now_add=True, verbose_name='время попытки')),
                ('attempt_status', models.BooleanField(default=False, verbose_name='статус')),
                ('server_response', models.CharField(blank=True, max_length=50, null=True, verbose_name='ответ сервера')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(verbose_name='тема')),
                ('body', models.TextField(blank=True, null=True, verbose_name='тело')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
    ]
