# Generated by Django 4.2.5 on 2023-09-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglogs',
            name='attempt_time',
            field=models.DateTimeField(verbose_name='время попытки'),
        ),
    ]
