# Generated by Django 4.2.5 on 2023-09-29 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailing_message_mailinglogs_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglogs',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing'),
        ),
    ]
