# Generated by Django 4.2.5 on 2023-09-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailinglogs_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='frequency',
            field=models.CharField(choices=[('ONCE', 'не повторять'), ('DAILY', 'ежедневно'), ('WEEKLY', 'еженедельно'), ('MONTHLY', 'ежемесячно')], default='ONCE', max_length=15, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('CREAT', 'создана'), ('START', 'запущена'), ('FIN', 'завершена')], default='CREAT', max_length=15, verbose_name='статус'),
        ),
    ]
