# Generated by Django 4.2.5 on 2023-09-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_mailing_frequency_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_time',
            field=models.TimeField(verbose_name='время'),
        ),
    ]
